extern XtAppContext app_context;
extern int colvmap[4][256];
extern char filcolvol[81];
extern float * fimage;
extern Pixmap imapsav;
extern int iwintyp;
extern int ncat;
extern FILE * resfp;
extern Boolean use3colors;
extern int vmap[256];
