#include <X11/Intrinsic.h>

extern float arealim;
extern char dfil1[12];
extern char dfil2[12];
extern char dfil3[12];
extern char dfil4[12];
extern char dfil5[12];
extern char dfil6[12];
extern int fitted;
extern float gammaff;
extern int iredu;
extern Widget iw_parlabel;
extern Widget iw_rowcolh0;
extern int maxpart;
extern int numm;
extern int orgkey;
extern float phif;
extern float thetaf;
extern float * xim;
extern float * xs;
extern float xs0t;
extern float * xs2;
extern float * xu0;
extern float xu0t;
extern float * ys;
extern float ys0t;
extern float * ys2;
extern float * yu0;
extern float yu0t;
