#! /bin/sh
#      
#
# normal usage: whichweb type (type: 2,3,4,5,6)
#
# selects target depending upon OS version & host

hostnow=`uname -n`
irixnow=`uname -r`
target="$1"

if [ "$hostnow" = "ithaca" -o "$hostnow" = "sylt" -o "$hostnow" = "barra" -o "$hostnow" = "nevis" -o "$hostnow" = "crete" -o "$hostnow" = "baffin" -o "$hostnow" = "flores" ]
   then
#  defaults to 4 on ithaca 
   which=4
   case "$target" in
   2 | -2 | 5 | -5)
      which=2;;
   3 | -3)
      which=3;;
   4 | -4 | 4mp | -4mp | mp | -mp)
      which=4;; 
   6 | -6)
      which=6;;
   ?*)
      echo "Bad version selector: $target for $hostnow"
      exit 1;; 
   esac

elif [ "$hostnow" = "borneo" -o "$hostnow" = "saba" -o "$hostnow" = "sicily" -o "$hostnow" = "ganga" -o "$hostnow" = "bali" ]
   then
#  defaults to 4 on borneo, saba, sicily, ganga, & bali
   which=4
   case "$target" in
   2 | -2 | 5 | -5)
      which=2;;
   3 | -3)
      which=3;;
   4 | -4 | 4mp | -4mp | mp | -mp)
      which=4;; 
   6 | -6)
      which=6;;
   ?*)
      echo "Bad version selector: $target for $hostnow"
      exit 1;; 
   esac

elif [ "$hostnow" = "jersey" -o "$hostnow" = "kyushu" ]
   then
#  defaults to 2 on jersey and kyushu
   which=2
   case "$target" in
   2 | -2 | 5 | -5)
      which=2;;
   3 | -3)
      which=3;;
   4 | -4 | 4mp | -4mp | mp | -mp)
      which=2;; 
   ?*)
      echo "Bad version selector: $target for $hostnow"
      exit 1;; 
   esac
elif [ "$hostnow" = "tioman.wadsworth.org" -o "$hostnow" = "aiolio.wadsworth.org" -o "$hostnow" = "ogygia.wadsworth.org" ]
      then
      which=_dec 

else
#   not running on ithaca or borneo
    if [ "$irixnow" = "5.3" ]
       then
#      default on Irix 5.3 is 2
       which=2
       case "$target" in
       2 | -2 | 5 | -5)
          which=2;;
       ?*)
         echo "Bad version selector: $target for $hostnow"
         exit 1;; 
      esac
    else
#      default on Irix 6.2 3 
       which=3
       case "$target" in
         2 | -2 | 5 | -5)
            which=2;;
         3 | -3)
           which=3;;
         ?*)
           echo "Bad version selector: $target for $hostnow"
           exit 1;;
       esac
    fi
fi
echo $which

exit 0
